name: Checks
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkou
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup pip
      run: pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Black
      run: black --diff --check $(git ls-files '*.py')
    - name: Run Pylint
      run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
    - name: Install Chromium
      run: apt-get install -y chromium-browser
    - name: Run Selenium Tests
      run: python jozef_wielogorka/manage.py test
